import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:hallmeal/screens/adminscreen/AdminLoginPage.dart';
import 'package:hallmeal/screens/adminscreen/AdminMenu.dart';
import 'package:hallmeal/screens/adminscreen/Meal/MealRequests.dart';
import 'package:hallmeal/screens/adminscreen/Meal/MelaMenu.dart';
import 'package:hallmeal/screens/studentscreen/MealBook/MealBook.dart';
import 'package:hallmeal/screens/studentscreen/StudentLoginPage.dart';
import 'firebase_options.dart'; // Import Firebase options generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home:  AdminMenu()


      // Determine where to navigate based on login state
    );
  }
}

